### PR TITLE
fixes #4

### LINKED ISSUE #4: Write a program to print "Hello World" using recursion

### PR DESCRIPTION
**Pull request by AnimeshKumar923**
Providing a solution to the issue #4 
Please review this and provide further feedback. Thank you.

### CODE REVIEW

**Review by iLakshya — APPROVED** [review]

**Review by iLakshya — APPROVED** [review]

**Comment by iLakshya** [comment]
Everything seems fine

**Comment by AnimeshKumar923** [comment]
Why close?

**Comment by AnimeshKumar923** [comment]
No mege? @iLakshya

**Comment by iLakshya** [comment]
I'll close all the PRs first then merge them into main

**Pull request closed without merging**
